### ISSUE TITLE
Vertical degree issue

### ISSUE THREAD

**Issue by briliantnugraha** [mvoelk/ssd_detectors#13]
Hi @mvoelk , good job here to reimplement a bunch of SSD variation with advanced and SoTA techniques. Can I ask you, you mention in https://github.com/mvoelk/ssd_detectors/blob/master/sl_utils.py#L290 that there is a vertical issue problem where it will become nan/inf. Is this has something to do with the way you wrap the dataset from .pkl or is this the issue with the decode function it self? do you have some direction on how to address this issue?

Thank you

**Comment by mvoelk** [comment]
I took a closer look and fixed the issue. It was the special case in which the decoder method performed a division by zero.

**Comment by briliantnugraha** [comment]
Got it, thank you for the prompt response!
