### ISSUE TITLE
[Question] performance about tbpp with focal loss but without DenseNet

### ISSUE THREAD

**Issue by JieZou1** [mvoelk/ssd_detectors#2]
Hi, 

I am trying to duplicate the tbpp512fl_synthtext experiment. After the 9th epoch completes, I have: val_precision: 0.8418 - val_recall: 0.6407 - val_accuracy: 0.5731 - val_fmeasure: 0.7189. 

It is far from "TextBoxes++ with DenseNet and Focal Loss" performance that you have reported on the ReadMe (0.901 precision, 0.931 recall and 0.916 fmeasure). It also looks to me that I will never reach 90+% performance.

I understand that I have not used DenseNet yet, and you also do not report "TextBoxes++ with Focal Loss" (without DenseNet). Since it will take me days to duplicate the experiment with "TextBoxes++ with DenseNet and Focal Loss", I want to understand whether the result that I obtained above for tbpp512fl_synthtext experiment is reasonable.

It is really surprising to me that using-or-not-using DenseNet would cause such large differences. So, please confirm if you got a chance. Many thanks indeed.

Best Regards
Jie

**Comment by mvoelk** [comment]
Hi,

the precision and recall values you refer to are evaluated on the local ground truth and the raw network output without decoding the bounding boxes and performing non-maximum suppression. They are evaluated on the most confident candidates for bounding boxes to get a rough impression during training.

For the evaluation procedure I used, see [TBPP_evaluate.ipynb](https://github.com/mvoelk/ssd_detectors/blob/master/TBPP_evaluate.ipynb)

Markus
