### ISSUE TITLE
Location of padding operation

### ISSUE THREAD

**Issue by eggcracker** [mvoelk/ssd_detectors#22]
Thanks for sharing your code. I have a comment regarding the location of the padding operation in ssd_data.py.
https://github.com/mvoelk/ssd_detectors/blob/3329c2e182f782bc36bd41e5b070483a378e7bd5/ssd_data.py#L538

I think it should be done before resizing the input image, not after, as we would like to preserve the aspect ratio of the original image. So, I think this version of the code has no effect on preserving the aspect ratio.

**Comment by mvoelk** [comment]
Fixed, thanks :)
