### ISSUE TITLE
May I ask for checkpoints?

### ISSUE THREAD

**Issue by mustardlove** [mvoelk/ssd_detectors#27]
Hello!
Thank you so much for your codes and help for everyone

I tried to run your *_train codes, but due to slow learning, I don't think I can ever complete the training..
Your *_evalute codes use trained weights (.h5), which I don't have, so I have trouble running those codes as well 

Would you mind providing checkpoints information...? 
It'd be great help if you could give me a hand
Thank you!

**Comment by mvoelk** [comment]
Would you mind to read the README...?
