### ISSUE TITLE
Is there a train code to train the entire end to end pipeline??

### ISSUE THREAD

**Issue by AyushP123** [mvoelk/ssd_detectors#28]
Hi,
      I was going through your code and wanted to ask, do we have to train SegLink and CRNN separately on our dataset or is there a code which does both simultaneously. 

I also wanted to ask for ICDAR2015FST do I have to specify the bounding boxes as:

> xmin, ymin, xmax, ymax

and for ICDAR2015IST the format is:

> x1, y1, x2, y2, x3, y3, x4, y4 ( The 4 points of the box in the anti-clockwise direction ).

**Comment by mvoelk** [comment]
No, you have to train them separately.

Yes, see #12.
