### ISSUE TITLE
Test TextBoxes++

### ISSUE THREAD

**Issue by manhntm3** [mvoelk/ssd_detectors#33]
Hi, I kinda newbie to git and CV here
How can I test the TextBoxes++ with my own images ? I can see SSD_predict.ipynb and SL_predict.ipynb but no TBPP_predict.ipynb in your git. Can you help me ?
Thanks in advance

**Comment by mvoelk** [comment]
You may find what you are looking for in TBPP_evaluate.ipynb

**Comment by mvoelk** [comment]
What you are looking for may be found in TBPP_evaluate.ipynb

**Comment by manhntm3** [comment]
Thanks for your reply
