### ISSUE TITLE
Textboxes++ training

### ISSUE THREAD

**Issue by eugene123tw** [mvoelk/ssd_detectors#34]
I'm trying to train my own textboxes++ using the ipython notebook you provided and I noticed an issue: 
* you use sigmoid (`model = TBPP512_dense(softmax=False)`) for the background and foreground class confidence instead of using softmax. However, the original SSD training used softmax. And it makes sense since it's not a multi-lable problem. Is there any reason using sigmoid?

**Comment by mvoelk** [comment]
To my knowledge, the classes in the multiclass case with sigmoid activation are less in conflict with each other then with softmax. In the one class case with sigmoid activation, you actually need only one output (conf_background = 1 - conf_text). 

To answer your question, there was no particular reason for me to use sigmoid in this case. So feel free to carry out further experiments... I would be interested in the results :)
