### ISSUE TITLE
sample_random_batch(), where is it?

### ISSUE THREAD

**Issue by krish240574** [mvoelk/ssd_detectors#4]
Hello, 
What is the sample_random_batch() function inside TBPP_train.ipynb? Is it part of the dict returned by pickle.load()? I'm sorry if I sound ignorant, I can't seem to find it anywhere, please advise. 

Thanks, 
Kumar

**Comment by mvoelk** [comment]
It is a method of the `GTUtility` class. I serialized the object in `datasets.ipynb` to avoid the preprocessing time of the dataset.

**Comment by mvoelk** [comment]
It is a method of the class `GTUtility`. I serialized the object in `datasets.ipynb` to avoid waiting during preprocessing the dataset.

**Comment by krish240574** [comment]
Woow, thanks, that was quick, much appreciated !

**Comment by krish240574** [comment]
Found it, it is inside ssd_data.py - the BaseGTUtility. Thank you once again. 
Kumar
