### ISSUE TITLE
TBPP++ How to visualize prior boxes

### ISSUE THREAD

**Issue by pai-dy** [mvoelk/ssd_detectors#40]
Hi, I'm university student of South Korea.

I'm in beginner level of deep learning.

Is there any way to visualize prior boxes on the syntext image? 

++ I want to know how to use function `plot_boxes` in PriorMaps and `plot` functions in PriorUtils

**Comment by mvoelk** [comment]
Try something like the following

```
for m in prior_util.prior_maps:
    plt.figure(figsize=[8]*2)
    plt.imshow(image)
    m.plot_locations()
    m.plot_boxes([0, 10, 100])
    plt.axis('off')
    plt.show()
```

**Comment by pai-dy** [comment]
Thank you for answer!

It did work!
