### ISSUE TITLE
TBPP model arbitrary input shape

### ISSUE THREAD

**Issue by pai-dy** [mvoelk/ssd_detectors#41]
Hi, I'm university student in Korea.

At first, Thank you for your help of my previous issue(visualizing).

This time, I wanted TBPP model's input shape to be arbitrary, so I set TBPP model's input shape as`image.shape`.

But when i adjust PriorUtil, because of assert code in [ssd_utils.py line.193](https://github.com/mvoelk/ssd_detectors/blob/f5b71b5438611b350083dac7de01e9ac16746cf4/ssd_utils.py#L193), I got an assertion error.

To avoid this error, I just erased assert code and I got an result as below
<img width="559" alt="스크린샷 2019-11-22 오후 1 56 23" src="https://user-images.githubusercontent.com/49555674/69399031-e849dc00-0d2f-11ea-9372-3a981f3608b1.png">
<img width="628" alt="스크린샷 2019-11-22 오후 1 56 08" src="https://user-images.githubusercontent.com/49555674/69399039-f1d34400-0d2f-11ea-9371-1ab301cb09e9.png">

Although I erased assert code, I think there is no problem so far.

Could you let me know why did you put assertion code and is there any problem when I erase assertion code in [ssd_utils.py line.193](https://github.com/mvoelk/ssd_detectors/blob/f5b71b5438611b350083dac7de01e9ac16746cf4/ssd_utils.py#L193)?

**Comment by mvoelk** [comment]
The motivation was to ensure that the size of the feature map gets reduced by a factor of 2 after downsampling. Furthermore, the prior boxes for the different locations on the feature map should be at the same location in the receptive field.

How did you solved the issue?

You may also be interested in reading #10...
