### ISSUE TITLE
Request to add .pkl files to repo

### ISSUE THREAD

**Issue by anindya7** [mvoelk/ssd_detectors#48]
Hi - as of now the .pkl files have to be generated from the datasets to run the *end2end* files. Requesting the owner to please upload these to the repo to allow running the code using weights files without having to download huge datasets.

**Comment by mvoelk** [comment]
You do not need the .pkl files, they do not contain any image data. However, you can feed any image data to the network... [sl_end2end_videotest.py](https://github.com/mvoelk/ssd_detectors/blob/master/sl_end2end_videotest.py) and [tbpp_end2end_videotest.py](https://github.com/mvoelk/ssd_detectors/blob/master/tbpp_end2end_videotest.py) are examples of how this can be done with a video stream. See also https://github.com/mvoelk/ssd_detectors/issues/8#issuecomment-456187638

Sorry, I don't want to add too many binary files to the repository and I'm not your Python or TensorFlow teacher either ;)

**Comment by anindya7** [comment]
The .pkl files are needed to avoid downloading the 40GB dataset, which is not possible for me (and likely others) under current conditions. Without either the .pkl or the dataset the code is not possible to run the network as the saved weights do not have necessary information. Since the repo is open source, it would be reasonable to expect the owner would like to make it independent. So no, you don't need to teach me as of now :) Anyway, thanks for your help.

**Comment by mvoelk** [comment]
@anindya7 The serialized code in the .pkl files still depends on the 40 GB image data!

**Comment by anindya7** [comment]
Understood! Thanks for pointing it out. I missed it.
