### ISSUE TITLE
fit_generator for ssd training & Check loss during training

### ISSUE THREAD

**Issue by pai-dy** [mvoelk/ssd_detectors#54]
hi, I'm trying to train ssd with COCO dataset using your "SSD_train.ipynb" script.

Is there any reason you didn't use fit_generator for training?

I want to check loss by iteration and check loss trend after training(by epoch).

**Is there any way to check loss&val_loss during training? and visualize loss trend after training(history)?** 

I used to check loss trend by save fit_generator as history.

Waiting for your answer. Thx.

**Comment by mvoelk** [comment]
see `plot_log.ipynb` and `plot_history.ipynb`...
