### ISSUE TITLE
training with own dataset resize issue

### ISSUE THREAD

**Issue by pai-dy** [mvoelk/ssd_detectors#55]
hi, I'm trying to train ssd with COCO dataset using your "SSD_train.ipynb" script.

I have my own image dataset and made annotation as COCO Json format.

My image dataset size is 1920X1080.

If resize 1920X1080 to (512,512) is it okay with annotation?

I mean that would resizing image affect training?

I thought that I have to calculate resize ratio and apply ratio to annotation as well.

**Comment by mvoelk** [comment]
Ground truth bounding boxes are resized by the preprocessing to the input size (512x512) and prediction is done in range (0,1). You have to resize the boxes by scaling them with the original image size. Just try to understand what the code is doing, it's not that hard ;)
