### ISSUE TITLE
TypeError: map() got an unexpected keyword argument 'deterministic' error

### ISSUE THREAD

**Issue by giwk2** [mvoelk/ssd_detectors#58]
hi I don't have good English skills so that I can ask my error in my code during following your SSD_train.ipynb.

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow.keras as keras
import os, time
from tqdm.notebook import tqdm
os.environ["CUDA_VISIBLE_DEVICES"] = '0'
from tensorflow.python.client import device_lib

from ssd_model import SSD300, SSD512
from ssd_utils import PriorUtil
from ssd_data import InputGenerator
from ssd_training import SSDLoss, SSDFocalLoss

from model import load_weights
from training import MetricUtility

from data_coco import GTUtility
gt_util = GTUtility('C:\\Users\\user')
gt_util_train, gt_util_val = gt_util.split(0.8)
experiment = 'ssd512_coco'
#print(gt_util)

#model = SSD300(num_classes=gt_util.num_classes)
model = SSD512(num_classes=gt_util.num_classes)

model.summary()

prior_util = PriorUtil(model)

weights_path = 'C:\\Users\\user\\vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5'
layer_list = [('block1_conv1', 'conv1_1'),
              ('block1_conv2', 'conv1_2'),
              ('block2_conv1', 'conv2_1'),
              ('block2_conv2', 'conv2_2'),
              ('block3_conv1', 'conv3_1'),
              ('block3_conv2', 'conv3_2'),
              ('block3_conv3', 'conv3_3'),
              ('block4_conv1', 'conv4_1'),
              ('block4_conv2', 'conv4_2'),
              ('block4_conv3', 'conv4_3'),
              ('block5_conv1', 'conv5_1'),
              ('block5_conv2', 'conv5_2'),
              ('block5_conv3', 'conv5_3')]

initial_epoch = 0

weights_path = './checkpoints/ssd512_coco_weights_fixed/ssd512_coco_weights_fixed.hdf5'
#weights_path = './checkpoints/201709251316_ssd512_coco/weights.040.h5'; initial_epoch = 41
#weights_path = './checkpoints/201709081909_ssd512_voc/weights.034.h5'; initial_epoch = 35
model.load_weights(weights_path, by_name=True)

freeze = ['conv1_1', 'conv1_2',
          'conv2_1', 'conv2_2',
          'conv3_1', 'conv3_2', 'conv3_3',
          #'conv4_1', 'conv4_2', 'conv4_3',
          #'conv5_1', 'conv5_2', 'conv5_3',
         ]

epochs = 100
batch_size = 24

#optimizer = keras.optimizers.SGD(lr=1e-3, momentum=0.9, decay=0, nesterov=True)
optimizer = keras.optimizers.Adam(lr=1e-4, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)

#loss = SSDLoss(alpha=1.0, neg_pos_ratio=3.0)
loss = SSDFocalLoss()

#regularizer = None
regularizer = keras.regularizers.l2(5e-4) # None if disabled

gen_train = InputGenerator(gt_util_train, prior_util, batch_size, model.image_size, augmentation=True)
gen_val = InputGenerator(gt_util_val, prior_util, batch_size, model.image_size, augmentation=True)

dataset_train = gen_train.get_dataset()
dataset_val = gen_val.get_dataset()
iterator_train = iter(dataset_train)
iterator_val = iter(dataset_val)

checkdir = './checkpoints/' + time.strftime('%Y%m%d%H%M') + '_' + experiment

if not os.path.exists(checkdir):
    os.makedirs(checkdir)

with open(checkdir+'/source.py','wb') as f:
    source = ''.join(['# In[%i]\n%s\n\n' % (i, In[i]) for i in range(len(In))])
    f.write(source.encode())

print(checkdir)

for l in model.layers:
    l.trainable = not l.name in freeze
    if regularizer and l.__class__.__name__.startswith('Conv'):
        model.add_loss(lambda l=l: regularizer(l.kernel))

metric_util = MetricUtility(loss.metric_names, logdir=checkdir)

@tf.function
def step(x, y_true, training=False):
    if training:
        with tf.GradientTape() as tape:
            y_pred = model(x, training=True)
            metric_values = loss.compute(y_true, y_pred)
            total_loss = metric_values['loss']
            if len(model.losses):
                total_loss += tf.add_n(model.losses)
        gradients = tape.gradient(total_loss, model.trainable_variables)
        optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    else:
        y_pred = model(x, training=True)
        metric_values = loss.compute(y_true, y_pred)
    return metric_values

for k in tqdm(range(initial_epoch, epochs), 'total', leave=False):
    print('\nepoch %i/%i' % (k+1, epochs))
    metric_util.on_epoch_begin()

    for i in tqdm(range(gen_train.num_batches), 'training', leave=False):
        x, y_true = next(iterator_train)
        metric_values = step(x, y_true, training=True)
        metric_util.update(metric_values, training=True)
    
    model.save_weights(checkdir+'/weights.%03i.h5' % (k+1,))

    for i in tqdm(range(gen_val.num_batches), 'validation', leave=False):
        x, y_true = next(iterator_val)
        metric_values = step(x, y_true, training=False)
        metric_util.update(metric_values, training=False)

    metric_util.on_epoch_end(verbose=1)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-df404371f1f4> in <module>
     15 
     16 
---> 17 dataset_train = gen_train.get_dataset()
     18 dataset_val = gen_val.get_dataset()
     19 iterator_train = iter(dataset_train)

C:\jupyterProject\Untitled Folder\ssd_data.py in get_dataset(self, num_parallel_calls, seed)
    561         ds = tf.data.Dataset.range(self.num_samples).repeat(-1).shuffle(self.num_samples)
    562         ds = ds.map(lambda x: tf.py_function(self.get_sample, [x, ], ['float32', 'float32']),
--> 563                     num_parallel_calls=tf.data.experimental.AUTOTUNE, deterministic=False)
    564 
    565         ds = ds.batch(self.batch_size).prefetch(tf.data.experimental.AUTOTUNE)

TypeError: map() got an unexpected keyword argument 'deterministic'

my tensorflow version is 2.1.0
tf.keras version is 2.2.4-tf

ssd_data.py - get_dataset is right this

    def get_dataset(self, num_parallel_calls=1, seed=1337):
        import tensorflow as tf

        if seed is not None:
            np.random.seed(seed)

        ds = tf.data.Dataset.range(self.num_samples).repeat(-1).shuffle(self.num_samples)
        ds = ds.map(lambda x: tf.py_function(self.get_sample, [x, ], ['float32', 'float32']),
                    num_parallel_calls=num_parallel_calls, deterministic=False)

        ds = ds.batch(self.batch_size).prefetch(tf.data.experimental.AUTOTUNE)

        return ds

I don't know this error.
TypeError: map() got an unexpected keyword argument 'deterministic'

How can I try to solve this problem? 

And do I have to give you my another code and other info? 

Thanks...

**Comment by giwk2** [comment]
I found this error I was changing my tensorflow version to 2.2.0 like your version.
So I finished this error. But I have a new error like this.

./checkpoints/202107060321_ssd512_coco
total: 0%
0/100 [00:48<?, ?it/s]

epoch 1/100
training: 0%
0/2736 [00:48<?, ?it/s]
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-5-df404371f1f4> in <module>
     60     for i in tqdm(range(gen_train.num_batches), 'training', leave=False):
     61         x, y_true = next(iterator_train)
---> 62         metric_values = step(x, y_true, training=True)
     63         metric_util.update(metric_values, training=True)
     64 

c:\users\엄희찬\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\eager\def_function.py in __call__(self, *args, **kwds)
    578         xla_context.Exit()
    579     else:
--> 580       result = self._call(*args, **kwds)
    581 
    582     if tracing_count == self._get_tracing_count():

c:\users\엄희찬\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\eager\def_function.py in _call(self, *args, **kwds)
    642         # Lifting succeeded, so variables are initialized and we can run the
    643         # stateless function.
--> 644         return self._stateless_fn(*args, **kwds)
    645     else:
    646       canon_args, canon_kwds = \

c:\users\엄희찬\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\eager\function.py in __call__(self, *args, **kwargs)
   2418     with self._lock:
   2419       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 2420     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2421 
   2422   @property

c:\users\엄희찬\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\eager\function.py in _filtered_call(self, args, kwargs)
   1663          if isinstance(t, (ops.Tensor,
   1664                            resource_variable_ops.BaseResourceVariable))),
-> 1665         self.captured_inputs)
   1666 
   1667   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

c:\users\엄희찬\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1744       # No tape is watching; skip to running the function.
   1745       return self._build_call_outputs(self._inference_function.call(
-> 1746           ctx, args, cancellation_manager=cancellation_manager))
   1747     forward_backward = self._select_forward_and_backward_functions(
   1748         args,

c:\users\엄희찬\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\eager\function.py in call(self, ctx, args, cancellation_manager)
    596               inputs=args,
    597               attrs=attrs,
--> 598               ctx=ctx)
    599         else:
    600           outputs = execute.execute_with_cancellation(

c:\users\엄희찬\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

ResourceExhaustedError:  OOM when allocating tensor with shape[24,64,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node model/conv1_1/Conv2D (defined at <ipython-input-5-df404371f1f4>:44) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_step_7509]

Errors may have originated from an input operation.
Input Source operations connected to node model/conv1_1/Conv2D:
 x (defined at <ipython-input-5-df404371f1f4>:62)

Function call stack:
step

CPU i5-6600 3.3GHz
my GPU is NVIDIA GeForce GTX 1060 3GB
RAM 8GB

Is it problem of batch size? Since my GPU memory too low to overwork?

Thanks...

**Comment by mvoelk** [comment]
The TensorFlow `dataset` API has changed in some ways, but the data pipeline I wrote is far from optimal anyway and most likely contains memory leaks.... In general, the tf1 branch can be an option if you don't want to improve it yourself.

OOM means out of memory. You can try to reduce the batch size, but I'm afraid 3 GB is too little for training. I had 11 GB at the beginning and 32 GB later. In the tf1 branch there is also an Adam optimizer that performs gradient accumulation...

**Comment by giwk2** [comment]
thanks~!!
