### ISSUE TITLE
Metrics issue ? 

### ISSUE THREAD

**Issue by NguyenThaiHoc1** [mvoelk/ssd_detectors#60]
Hello mvoelk
I have a question about metrics ("precision", "recall", "f-measure")
The function  at https://github.com/mvoelk/ssd_detectors/blob/master/ssd_training.py

``
def compute_metrics(class_true, class_pred, conf, top_k=100): 
``
I saw you pass-through **max confidence index of each batch in each default box** in this function 

But according to what I have learned, we need to pass through box location and _**we can get IoU of predicting box union with box Ground-Truth**_ , we can get TP and FP and FN of all samples which based on a threshold, So we will calculate precision and recall of all samples. 

Can you explain your ideas ?

Thank you so much 
Thai Hoc

**Comment by mvoelk** [comment]
https://github.com/mvoelk/ssd_detectors/issues/2#issuecomment-417882317

I hope this answers your question :)

**Comment by NguyenThaiHoc1** [comment]
> [#2 (comment)](https://github.com/mvoelk/ssd_detectors/issues/2#issuecomment-417882317)
> 
> I hope this answers your question :)

Hi 
When I saw your answer. you evaluated the most confident candidates for bounding boxes. Why don't you use IoU for each box which has high confidence. I think if you don't when you predict it may be skewed to other side compared to the GT box?

Thank you for your reply.

**Comment by mvoelk** [comment]
I assume
https://github.com/mvoelk/ssd_detectors/blob/6fe86b18fc7e514ff54bde43e570825ff3ba2137/ssd_metric.py#L14
for axis aligned bounding boxes, and
https://github.com/mvoelk/ssd_detectors/blob/6fe86b18fc7e514ff54bde43e570825ff3ba2137/sl_metric.py#L10
for polygons, is what you are looking for.

**Comment by NguyenThaiHoc1** [comment]
Thank you so much that all i need to see
