### ISSUE TITLE
[Question] Where to get dataset used for training CRNN (ICDAR2013)?

### ISSUE THREAD

**Issue by sniper0110** [mvoelk/ssd_detectors#7]
Hello again,

I just wanted to know where you got the ICDAR2013 dataset to train your CRNN model? I found other datasets here : http://rrc.cvc.uab.es but I can't find ICDAR2013. 

In fact, I just want to run your code for training CRNN just to see the workflow and then change the dataset to my own customed one.

Thanks in advance!

**Comment by mvoelk** [comment]
If I remember it right, it is identical to the ICDAR 2015 Focused Scene Text dataset. I will update the notebooks.
