### ISSUE TITLE
About Textboxes++

### ISSUE THREAD

**Issue by ld20242025** [mvoelk/ssd_detectors#9]
could you  give me the textboxes++ code of keras? I can't train and test the textboxes++ model.Thanks

**Comment by mvoelk** [comment]
Can you be a bit more precise?

The relevant files are named `TBPP_*.ipynb` and `tbpp_*.py`. For trained models, see `README.md`.

**Comment by ld20242025** [comment]
when i try to run the TBPP_evaluate.py,the errors predicts 'TypeError: src data type = 17 is not supported'.
And i make sure the the path of model and synthtext-datast is right.Please tell me what's wrong with it.
(Traceback (most recent call last):
  File "D:/kerasoftextboxes++/TBPP_evaluate.py", line 35, in <module>
    _, inputs, images, data = gt_util_val.sample_random_batch(1024)
  File "D:\kerasoftextboxes++\ssd_data.py", line 152, in sample_random_batch
    inputs.append(preprocess(img, input_size))
  File "D:\kerasoftextboxes++\ssd_data.py", line 623, in preprocess
    img = cv2.resize(img, (w,h), cv2.INTER_LINEAR)
TypeError: src data type = 17 is not supported)

**Comment by mvoelk** [comment]
Seems like a type issue and may depend the OpenCV version... please let us know how you solved it.
